### PR TITLE
Feature/rearranging

### PR DESCRIPTION
**Pull request by Benjamin-Etheredge**
Current status of moving stuff around.
I can't seem to get *-Recommendation.ipynb to run.

### CODE REVIEW

**Comment by Benjamin-Etheredge** [comment]
The one change I didn't add was where I added "df.to_csv(path, index_header=False)" to some of the notebooks. I'm not sure what to do with the notebooks yet. I also couldn't seem to get the gz files to work well with "dvc.api.open".

**Comment by jperiodlangley** [comment]
I wonder if the gz open issue is due to them being written with a different version of python? I think that's what I was having issues with for the streamlit share server.

**Comment by Benjamin-Etheredge** [comment]
It might be. The issues stems from having to stream the data. I can't just pass the file name to pandas. I had to open the gz file and pass the file handle. I'll test regenerating the data though.

**Comment by Benjamin-Etheredge** [comment]
I still can't get *-Recommendation.ipynb to run. It keeps hanging and crashing with the wandb integration. I added a limit to the number of runs, but it never makes it that far. It hangs on "run.finish()". It seems the wandb run never logs anything before crashing.

**Comment by Benjamin-Etheredge** [comment]
I switched it over to using csv rather than compressed data. 
I also commented out where it was hanging in the notebook and cleared output.
It should be ready to merge now.

**Pull request merged**
